# Generated by Django 2.1.3 on 2018-11-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('student_name', models.CharField(max_length=40)),
                ('student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('student_photo', models.ImageField(upload_to='')),
                ('student_class', models.CharField(max_length=10)),
                ('student_section', models.CharField(max_length=1)),
            ],
        ),
    ]
