# Generated by Django 2.1.3 on 2018-11-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20181124_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='name',
            field=models.CharField(default='1', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='numeric_class',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='student_name',
        ),
    ]
