# Generated by Django 2.1.3 on 2018-12-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20181124_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.StudentClass'),
        ),
    ]
