# Generated by Django 2.1.3 on 2018-11-23 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_class', models.CharField(max_length=15)),
                ('student_section', models.CharField(max_length=2)),
                ('payment_type', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 11, 23, 4, 5, 14, 564333))),
            ],
        ),
    ]
