# Generated by Django 2.1.3 on 2018-11-24 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181124_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 6, 46, 36, 923664)),
        ),
    ]
