# Generated by Django 2.1.3 on 2018-11-26 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181124_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 19, 7, 9, 663408)),
        ),
    ]
