# Generated by Django 2.1.3 on 2018-11-26 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181126_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 19, 51, 43, 61368)),
        ),
    ]
