# Generated by Django 2.1.3 on 2018-11-26 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181126_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 19, 53, 9, 836775)),
        ),
    ]
